import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { Footer, Header, Inquiry } from "../../components";
const cities: Record<string, { name: string; nearby: string }> = {
  mcallen: { name: "McAllen", nearby: "Edinburg, Pharr, Mission, and across the RGV" }, edinburg: { name: "Edinburg", nearby: "McAllen, Pharr, Mission, and across the RGV" }, mission: { name: "Mission", nearby: "McAllen, Palmhurst, La Joya, and across the RGV" }, weslaco: { name: "Weslaco", nearby: "Mercedes, Donna, McAllen, and across the RGV" }, pharr: { name: "Pharr", nearby: "McAllen, San Juan, Edinburg, and across the RGV" }, harlingen: { name: "Harlingen", nearby: "San Benito, Brownsville, Weslaco, and across the RGV" }, brownsville: { name: "Brownsville", nearby: "Los Fresnos, Harlingen, South Padre Island, and across the RGV" }
};
export function generateStaticParams() { return Object.keys(cities).map((city) => ({ city })); }
export async function generateMetadata({ params }: { params: Promise<{ city: string }> }): Promise<Metadata> { const { city } = await params; const place = cities[city]; return place ? { title: `DJ in ${place.name}, TX`, description: `Sound Factory Productions provides DJ services for celebrations and events in ${place.name}, Texas and the Rio Grande Valley.` } : {}; }
export default async function CityPage({ params }: { params: Promise<{ city: string }> }) { const { city } = await params; const place = cities[city]; if (!place) notFound(); return <><Header /><main><section className="page-hero"><p className="eyebrow">RIO GRANDE VALLEY DJ SERVICES</p><h1>DJ services in {place.name}, Texas</h1><p>Sound Factory Productions brings music and celebration energy to events in {place.name} and throughout the Rio Grande Valley.</p></section><section className="content"><div><p className="eyebrow">LOCAL SERVICE</p><h2>Celebrating {place.name} in full volume.</h2></div><div><p>Whether you’re planning a wedding, quinceañera, private party, or corporate celebration, Sound Factory Productions is ready to help your event feel special from start to finish.</p><p>We serve {place.name}, plus {place.nearby}.</p><Link className="text-link" href="/services/wedding-dj">Explore DJ services →</Link></div></section><Inquiry title={`Looking for a DJ in ${place.name}?`} /></main><Footer /></>; }
