"use client";
import { FormEvent, useEffect, useState } from "react";

type Role = "owner" | "admin" | "staff";
type User = { id: number; email: string; name: string; role: Role; active: boolean; last_login_at: string | null };
type Lead = { id: number; name: string; email: string; phone: string; event_type: string; event_city: string | null; package_name: string };
type Dashboard = { visits: number; leads: number; conversion: number; recentLeads: Lead[]; user: User };

export function AdminPanel() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [users, setUsers] = useState<User[]>([]); const [newUser, setNewUser] = useState({ name: "", email: "", password: "", role: "staff" as Role }); const [userMessage, setUserMessage] = useState("");
  const loadDashboard = async () => { const response = await fetch("/api/admin"); if (response.ok) setDashboard(await response.json()); setLoading(false); };
  useEffect(() => { loadDashboard(); }, []);
  useEffect(() => { if (dashboard?.user.role === "owner") fetch("/api/admin/users").then(async (response) => response.ok && setUsers((await response.json()).users)); }, [dashboard?.user.role]);
  async function signIn(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (response.ok) { await loadDashboard(); } else { setError((await response.json().catch(() => ({}))).error || "The dashboard is not ready yet."); setLoading(false); } }
  async function signOut() { await fetch("/api/admin", { method: "DELETE" }); setDashboard(null); setUsers([]); setEmail(""); setPassword(""); }
  async function addUser(event: FormEvent) { event.preventDefault(); setUserMessage(""); const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(newUser) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setUserMessage(data.error || "Could not create the user."); return; } setUsers((current) => [...current, data.user]); setNewUser({ name: "", email: "", password: "", role: "staff" }); setUserMessage("User created."); }
  async function toggleUser(user: User) { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: user.id, active: !user.active }) }); const data = await response.json().catch(() => ({})); if (response.ok) setUsers((current) => current.map((item) => item.id === user.id ? data.user : item)); else setUserMessage(data.error || "Could not update user."); }
  if (loading && !dashboard) return <main className="admin"><p className="eyebrow">SOUND FACTORY BACK OFFICE</p><p>Loading secure dashboard…</p></main>;
  if (!dashboard) return <main className="admin"><p className="eyebrow">SOUND FACTORY BACK OFFICE</p><h1>Admin sign in</h1><p className="admin-note">Secure access for the Sound Factory team.</p><form className="admin-login" onSubmit={signIn}><label>Admin email<input required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input required type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="button" disabled={loading}>{loading ? "Signing in…" : "Sign in"}</button></form></main>;
  const isOwner = dashboard.user.role === "owner";
  return <main className="admin"><div className="admin-top"><div><p className="eyebrow">SOUND FACTORY BACK OFFICE</p><h1>Traffic & inquiries</h1></div><div><span className="admin-user">{dashboard.user.name} · {dashboard.user.role}</span><button className="text-button" onClick={signOut}>Sign out</button></div></div><section className="metrics"><div><b>{dashboard.visits}</b><span>30-day visits</span></div><div><b>{dashboard.leads}</b><span>30-day leads</span></div><div><b>{dashboard.conversion.toFixed(1)}%</b><span>Conversion</span></div></section><section className="admin-section"><h2>Recent inquiries</h2><div className="lead-list">{dashboard.recentLeads.length ? dashboard.recentLeads.map((lead) => <article key={lead.id}><b>{lead.name}</b><p>{lead.event_type} · {lead.package_name} · {lead.event_city || "City TBD"}</p><a href={`mailto:${lead.email}`}>{lead.email}</a> · <a href={`tel:${lead.phone}`}>{lead.phone}</a></article>) : <p>No inquiries yet.</p>}</div></section>{isOwner && <section className="admin-section user-management"><div><p className="eyebrow">TEAM ACCESS</p><h2>Manage users</h2><p className="admin-note">Create accounts, choose a role, or turn access off when someone no longer needs the dashboard.</p></div><form className="user-form" onSubmit={addUser}><label>Name<input required value={newUser.name} onChange={(event) => setNewUser({ ...newUser, name: event.target.value })} /></label><label>Email<input required type="email" value={newUser.email} onChange={(event) => setNewUser({ ...newUser, email: event.target.value })} /></label><label>Temporary password<input required minLength={10} type="password" value={newUser.password} onChange={(event) => setNewUser({ ...newUser, password: event.target.value })} /></label><label>Role<select value={newUser.role} onChange={(event) => setNewUser({ ...newUser, role: event.target.value as Role })}><option value="staff">Staff — dashboard access</option><option value="admin">Admin — dashboard access</option><option value="owner">Owner — manage users</option></select></label><button className="button">Create user</button>{userMessage && <p className="form-error">{userMessage}</p>}</form><div className="user-list">{users.map((user) => <article key={user.id}><div><b>{user.name}</b><p>{user.email} · {user.role}</p></div><button className="status-button" disabled={user.id === dashboard.user.id} onClick={() => toggleUser(user)}>{user.active ? "Active" : "Inactive"}</button></article>)}</div></section>}</main>;
}
