import Link from "next/link";
import Image from "next/image";
import { Footer, Header, Inquiry } from "./components";
import { PackageBuilder } from "./package-builder";
import { MotionEffects } from "./motion-effects";

const services = [
  ["Wedding DJs", "Music that supports every chapter of your celebration.", "wedding-dj"],
  ["Quinceañera DJs", "A polished soundtrack for a night everyone will remember.", "quinceanera-dj"],
  ["Private Events", "Birthday parties, anniversaries, reunions, and more.", "private-event-dj"],
  ["Corporate Events", "Professional music support for company gatherings and celebrations.", "corporate-event-dj"]
];
const cities = ["McAllen", "Edinburg", "Mission", "Weslaco", "Pharr", "Harlingen", "Brownsville"];
const signatureCapabilities = ["DJ + MC", "Lighting design", "LED screens", "Cold sparklers", "Custom dance floors", "Photo booths"];

export default function Home() {
  return <><Header /><main><section className="hero hero-photo"><Image src="/wedding-sparklers.jpeg" alt="Newlyweds sharing a dance beneath celebration sparklers" fill priority sizes="100vw" className="hero-image" /><div className="hero-shade" /><MotionEffects /><div className="hero-copy"><p className="eyebrow">MCALLEN · RIO GRANDE VALLEY</p><h1>Make it feel<br /><em>like a movie.</em></h1><p className="lede">DJ entertainment and elevated event production for weddings, quinceañeras, and unforgettable celebrations across the Rio Grande Valley.</p><a className="button" href="#build-package">Check your date</a></div></section>
  <section className="production-strip" aria-label="Event production specialties">{signatureCapabilities.map((capability) => <span key={capability}>✦ {capability}</span>)}</section>
  <section className="video-reel" aria-label="Event production in motion"><div className="video-reel-copy"><p className="eyebrow">THE ENERGY IS REAL</p><h2>Every detail moves.</h2><p>From the first cue to the last song, we build an atmosphere guests can feel.</p></div><div className="reel-grid"><figure className="reel-dj"><video autoPlay muted loop playsInline preload="metadata" poster="/custom-led-display.jpeg" aria-label="DJ mixing music at an event"><source src="/pexels-dj-loop.mp4" type="video/mp4" /></video><figcaption>Sound, dialed in.</figcaption></figure><figure className="reel-wedding"><video autoPlay muted loop playsInline preload="metadata" poster="/wedding-sparklers.jpeg" aria-label="Couple dancing beneath wedding lights"><source src="/pexels-wedding-loop.mp4" type="video/mp4" /></video><figcaption>Your moment.</figcaption></figure><figure className="reel-production"><video autoPlay muted loop playsInline preload="metadata" poster="/venue-uplighting.jpeg" aria-label="Event stage prepared with production lighting"><source src="/pexels-production-loop.mp4" type="video/mp4" /></video><figcaption>Built with intention.</figcaption></figure></div></section>
  <section className="intro intro-statement"><div><p className="eyebrow">MORE THAN A PLAYLIST</p><h2>Sound, lighting, and a room that feels completely transformed.</h2><p>The work speaks for itself: custom visual moments, uplighting, statement dance floors, and a packed dance-floor energy built around your celebration.</p></div><aside><span>FACTORY RGV</span><strong>Designed around your moment.</strong><p>Every setup is built to look as unforgettable as it sounds.</p></aside></section>
  <section className="feature-image"><Image src="/venue-uplighting.jpeg" alt="Elegant event venue transformed with purple uplighting" width={1600} height={900} sizes="(max-width: 720px) 100vw, 84vw" /><p>Atmosphere is everything.</p></section>
  <section className="grid-section"><div className="section-heading"><p className="eyebrow">EVENT SERVICES</p><h2>For the moments that matter.</h2><p>Choose the energy. We’ll build the atmosphere around it.</p></div><div className="cards">{services.map(([name, description, slug], index) => <Link className="card" href={`/services/${slug}`} key={name}><small>0{index + 1}</small><span className="card-mark">✦</span><h3>{name}</h3><p>{description}</p><span className="service-arrow">Explore service <b>→</b></span></Link>)}</div></section>
  <section className="gallery"><div className="section-heading"><p className="eyebrow">REAL EVENTS · REAL MOMENTS</p><h2>Built to be remembered.</h2></div><div className="gallery-grid"><figure className="gallery-tall"><Image src="/mirrored-dance-floor.jpeg" alt="Couple dancing on a mirrored wedding dance floor" fill sizes="(max-width: 720px) 100vw, 42vw" /><figcaption>Mirrored dance floor</figcaption></figure><figure><Image src="/custom-led-display.jpeg" alt="Custom LED display at a quinceañera celebration" fill sizes="(max-width: 720px) 100vw, 42vw" /><figcaption>Custom LED display</figcaption></figure><figure><Image src="/photo-booth.jpeg" alt="Custom photo booth installation at an event" fill sizes="(max-width: 720px) 100vw, 42vw" /><figcaption>Photo booth experience</figcaption></figure></div></section>
  <section className="production-signature"><div><p className="eyebrow">THE FACTORY RGV STANDARD</p><h2>Production that makes the room feel different.</h2></div><p>Music is only the beginning. From the grand entrance through the last song, every detail is designed to keep the energy moving and the cameras rolling.</p><a href="#build-package">Build your experience <span>↘</span></a></section>
  <section className="locations"><p className="eyebrow">SOUND ACROSS THE VALLEY</p><h2>Your DJ, wherever the party is.</h2><div>{cities.map((city) => <Link href={`/locations/${city.toLowerCase()}`} key={city}>{city} <span>↗</span></Link>)}</div></section><PackageBuilder /><Inquiry /></main><Footer /></>;
}
