import Link from "next/link";
import Image from "next/image";
import { Footer, Header, Inquiry } from "./components";
import { PackageBuilder } from "./package-builder";
import { MotionEffects } from "./motion-effects";

const services = [
  ["Wedding DJs", "Music that supports every chapter of your celebration.", "wedding-dj"],
  ["Quinceañera DJs", "A polished soundtrack for a night everyone will remember.", "quinceanera-dj"],
  ["Cheerleading Events", "High-energy sound and production for showcases, competitions, and team celebrations.", "cheerleading-event-dj"],
  ["Private Events", "Birthday parties, anniversaries, reunions, and more.", "private-event-dj"],
  ["Corporate Events", "Professional music support for company gatherings and celebrations.", "corporate-event-dj"],
  ["Concerts & Public Events", "Sound, lighting, LED visuals, and show-ready production for live crowds.", "concert-production"]
];
const cities = ["McAllen", "Edinburg", "Mission", "Weslaco", "Pharr", "Harlingen", "Brownsville"];
const signatureCapabilities = ["DJ + MC", "Lighting design", "LED screens", "Cold sparklers", "Custom dance floors", "Photo booths"];

export default function Home() {
  return <><Header /><main><section className="hero hero-photo"><Image src="/wedding-sparklers.jpeg" alt="Newlyweds sharing a dance beneath celebration sparklers" fill priority sizes="100vw" className="hero-image" /><div className="hero-shade" /><MotionEffects /><div className="hero-copy"><p className="eyebrow">MCALLEN · RIO GRANDE VALLEY</p><h1>Make it feel<br /><em>like a movie.</em></h1><p className="lede">DJ entertainment and elevated event production for celebrations, cheerleading events, corporate gatherings, and public events across the Rio Grande Valley.</p><a className="button" href="#build-package">Check your date</a></div></section>
  <section className="production-strip" aria-label="Event production specialties">{signatureCapabilities.map((capability) => <span key={capability}>✦ {capability}</span>)}</section>
  <section className="video-reel" aria-label="Sound Factory event production in motion"><div className="video-reel-copy"><h2>Built for the moments people replay.</h2><p>From a packed dance floor to a show-ready stage, every cue is designed to look as good as it feels.</p></div><div className="reel-grid"><figure className="reel-dj"><video autoPlay muted loop playsInline preload="metadata" poster="/event-ambience.jpg" aria-label="Guests enjoying a Sound Factory dance floor"><source src="/event-ambience.mp4" type="video/mp4" /></video><figcaption>Dance-floor energy.</figcaption></figure><figure className="reel-wedding"><video autoPlay muted loop playsInline preload="metadata" poster="/wedding-confetti.jpg" aria-label="Wedding confetti moment at a Sound Factory event"><source src="/wedding-confetti.mp4" type="video/mp4" /></video><figcaption>The big finish.</figcaption></figure><figure className="reel-production"><video autoPlay muted loop playsInline preload="metadata" poster="/cheer-stage.jpg" aria-label="Cheer competition stage prepared with Sound Factory lighting and production"><source src="/cheer-stage.mp4" type="video/mp4" /></video><figcaption>Show-ready production.</figcaption></figure></div></section>
  <section className="intro intro-statement"><div><h2>Sound, lighting, and a room that feels completely transformed.</h2><p>The work speaks for itself: custom visual moments, uplighting, statement dance floors, and a packed dance-floor energy built around your celebration.</p></div><aside><span>FACTORY RGV</span><strong>Designed around your moment.</strong><p>Every setup is built to look as unforgettable as it sounds.</p></aside></section>
  <section className="feature-image"><Image src="/venue-uplighting.jpeg" alt="Elegant event venue transformed with purple uplighting" width={1600} height={900} sizes="(max-width: 720px) 100vw, 84vw" /><p>Atmosphere is everything.</p></section>
  <section className="grid-section" id="services"><div className="section-heading"><p className="eyebrow">EVENT SERVICES</p><h2>For the moments that matter.</h2><p>From a packed dance floor to a full cheer showcase, we’ll build the atmosphere around the occasion.</p></div><div className="cards">{services.map(([name, description, slug], index) => <Link className="card" href={`/services/${slug}`} key={name}><small>0{index + 1}</small><span className="card-mark">✦</span><h3>{name}</h3><p>{description}</p><span className="service-arrow">Explore service <b>→</b></span></Link>)}</div></section>
  <section className="gallery"><div className="section-heading"><h2>Built to be remembered.</h2></div><div className="gallery-grid"><figure className="gallery-tall"><Image src="/mirrored-dance-floor.jpeg" alt="Couple dancing on a mirrored wedding dance floor" fill sizes="(max-width: 720px) 100vw, 42vw" /><figcaption>Mirrored dance floor</figcaption></figure><figure><Image src="/custom-led-display.jpeg" alt="Custom LED display at a quinceañera celebration" fill sizes="(max-width: 720px) 100vw, 42vw" /><figcaption>Custom LED display</figcaption></figure><figure><Image src="/photo-booth.jpeg" alt="Custom photo booth installation at an event" fill sizes="(max-width: 720px) 100vw, 42vw" /><figcaption>Photo booth experience</figcaption></figure></div></section>
  <section className="production-signature"><div><h2>Production that makes the room feel different.</h2></div><p>Music is only the beginning. From the grand entrance through the last song, every detail is designed to keep the energy moving and the cameras rolling.</p><a href="#build-package">Build your package <span>↘</span></a></section>
  <section className="locations locations-grid"><div className="locations-grid__intro"><p>Serving the Rio Grande Valley</p><h2>Your DJ, wherever the party is.</h2></div><div className="locations-grid__list">{cities.map((city) => <Link href={`/locations/${city.toLowerCase()}`} key={city}><span>{city}</span></Link>)}</div></section><PackageBuilder /><Inquiry /></main><Footer /></>;
}
