"use client";

import { FormEvent, useState } from "react";

const extras = ["Pista de baile personalizada", "Chisperos fríos interiores", "Efecto de niebla baja", "Cañón de confeti", "Efecto de burbujas", "Props personalizados", "Show de fuegos artificiales de 1 minuto", "Show de fuegos artificiales de 2-3 minutos"];

export function SpanishPackageBuilder() {
  const [sent, setSent] = useState(false); const [sending, setSending] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ eventType: "Boda", eventDate: "", eventCity: "McAllen", venue: "", packageName: "Signature", addons: [] as string[], name: "", email: "", phone: "", notes: "" });
  const update = (key: string, value: string | string[]) => setForm((state) => ({ ...state, [key]: value }));
  const toggle = (item: string) => update("addons", form.addons.includes(item) ? form.addons.filter((value) => value !== item) : [...form.addons, item]);
  async function submit(event: FormEvent) { event.preventDefault(); setSending(true); setError(""); const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setSending(false); if (response.ok) setSent(true); else setError((await response.json()).error || "No pudimos guardar tu solicitud."); }
  if (sent) return <section className="builder"><p className="eyebrow">SOLICITUD RECIBIDA</p><h2>Ya falta poco para una celebración inolvidable.</h2><p>Gracias, {form.name}. Nuestro equipo se pondrá en contacto contigo pronto.</p></section>;
  return <section className="builder" id="build-package"><p className="eyebrow">PLANEA TU EXPERIENCIA</p><h2>Crea tu paquete.</h2><p className="builder-intro">Cuéntanos lo esencial y envía tu solicitud directamente a nuestro equipo.</p><form onSubmit={submit} className="builder-step"><label>¿Qué estás planeando?<select value={form.eventType} onChange={(e) => update("eventType", e.target.value)}><option>Boda</option><option>Quinceañera</option><option>Evento de cheerleading</option><option>Evento escolar o de equipo</option><option>Cumpleaños</option><option>Evento corporativo</option><option>Celebración privada</option><option>Otro</option></select></label><label>Fecha del evento<input type="date" value={form.eventDate} onChange={(e) => update("eventDate", e.target.value)} /></label><label>Ciudad<input value={form.eventCity} onChange={(e) => update("eventCity", e.target.value)} /></label><label>Salón o venue (si lo conoces)<input value={form.venue} onChange={(e) => update("venue", e.target.value)} /></label><div className="package-options"><button type="button" className={form.packageName === "Signature" ? "selected" : ""} onClick={() => update("packageName", "Signature")}><b>Signature</b><span>6 horas · DJ y MC · audio e iluminación profesional · pantalla LED · iluminación arquitectónica.</span></button><button type="button" className={form.packageName === "Deluxe" ? "selected" : ""} onClick={() => update("packageName", "Deluxe")}><b>Deluxe</b><span>Todo Signature, más banner LED, efectos especiales, props personalizados y personal de evento.</span></button><button type="button" className={form.packageName === "Custom" ? "selected" : ""} onClick={() => update("packageName", "Custom")}><b>Personalizado</b><span>Cuéntanos tu visión y crearemos el plan ideal.</span></button></div><p className="addon-label">Mejoras opcionales</p><div className="addons">{extras.map((item) => <label key={item}><input type="checkbox" checked={form.addons.includes(item)} onChange={() => toggle(item)} />{item}</label>)}</div><label>Tu nombre<input required value={form.name} onChange={(e) => update("name", e.target.value)} /></label><label>Correo electrónico<input required type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></label><label>Teléfono<input required type="tel" value={form.phone} onChange={(e) => update("phone", e.target.value)} /></label><label>Detalles adicionales<textarea rows={4} value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="button" disabled={sending}>{sending ? "Enviando…" : "Enviar mi solicitud"}</button></form></section>;
}
