import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer, Header, Inquiry } from "../../components";
import { SpanishPackageBuilder } from "../../spanish-package-builder";
import { locations, rgvLocationSlugs, texasTravelLocationSlugs } from "../../locations/data";

const cities: Record<string, string> = { texas: "todo Texas", ...Object.fromEntries([...rgvLocationSlugs, ...texasTravelLocationSlugs].map((slug) => [slug, locations[slug].name])) };
const services: Record<string, { name: string; text: string }> = { "wedding-dj": { name: "DJ para Bodas", text: "Música, producción y momentos que acompañan cada parte de tu celebración." }, "quinceanera-dj": { name: "DJ para Quinceañeras", text: "Una experiencia elegante, energética y diseñada para una noche inolvidable." }, "cheerleading-event-dj": { name: "DJ para Eventos de Cheerleading", text: "Sonido, energía y producción para showcases, competencias, premiaciones y celebraciones de equipo." }, "private-event-dj": { name: "DJ para Eventos Privados", text: "Música y ambiente para cumpleaños, aniversarios, graduaciones, reuniones y celebraciones especiales." }, "corporate-event-dj": { name: "DJ para Eventos Corporativos", text: "Producción profesional para fiestas de empresa, activaciones de marca y celebraciones de equipo." }, "concert-production": { name: "Conciertos y Eventos Públicos", text: "Audio, iluminación, pantallas LED y producción lista para escenarios y público en vivo." } };

export function generateStaticParams() { return [[], ["services", "wedding-dj"], ["services", "quinceanera-dj"], ["services", "cheerleading-event-dj"], ["services", "private-event-dj"], ["services", "corporate-event-dj"], ["services", "concert-production"], ...Object.keys(cities).map((city) => ["locations", city])].map((slug) => ({ slug })); }
export default async function SpanishPage({ params }: { params: Promise<{ slug?: string[] }> }) { const { slug = [] } = await params; if (!slug.length) return <Home />; if (slug[0] === "services" && services[slug[1]]) return <Service item={services[slug[1]]} />; if (slug[0] === "locations" && cities[slug[1]]) return <City city={cities[slug[1]]} />; notFound(); }
function Home() { return <><Header locale="es" /><main><section className="hero hero-photo"><Image src="/wedding-sparklers.jpeg" alt="Recién casados bailando bajo luces y efectos de celebración" fill priority sizes="100vw" className="hero-image" /><div className="hero-shade" /><div className="hero-copy"><p className="eyebrow">MCALLEN · VALLE DEL RÍO GRANDE</p><h1>Haz que se sienta<br /><em>como una película.</em></h1><p className="lede">DJ y producción para celebraciones, eventos de cheerleading, eventos corporativos y eventos públicos en todo el Valle del Río Grande.</p><a className="button" href="#build-package">Consulta tu fecha</a></div></section><section className="intro"><p className="eyebrow">MÁS QUE UNA LISTA DE MÚSICA</p><h2>Sonido, iluminación y un espacio completamente transformado.</h2><p>Momentos visuales a la medida, iluminación arquitectónica, pistas que hacen una declaración y energía diseñada alrededor de tu celebración.</p></section><section className="feature-image"><Image src="/venue-uplighting.jpeg" alt="Salón elegante con iluminación morada" width={1600} height={900} sizes="(max-width: 720px) 100vw, 84vw" /><p>La atmósfera lo es todo.</p></section><section className="grid-section" id="services"><div className="section-heading"><p className="eyebrow">SERVICIOS</p><h2>Para momentos que importan.</h2></div><div className="cards">{Object.entries(services).map(([slug, item], index) => <Link className="card" href={`/es/services/${slug}`} key={slug}><small>0{index + 1}</small><h3>{item.name}</h3><p>{item.text}</p><span>Conoce el servicio →</span></Link>)}</div></section><section className="gallery"><div className="section-heading"><p className="eyebrow">EVENTOS REALES · MOMENTOS REALES</p><h2>Hecho para recordarse.</h2></div><div className="gallery-grid"><figure className="gallery-tall"><Image src="/mirrored-dance-floor.jpeg" alt="Pareja bailando en una pista espejo" fill sizes="(max-width: 720px) 100vw, 42vw" /></figure><figure><Image src="/custom-led-display.jpeg" alt="Pantalla LED personalizada" fill sizes="(max-width: 720px) 100vw, 42vw" /></figure><figure><Image src="/photo-booth.jpeg" alt="Instalación de foto booth" fill sizes="(max-width: 720px) 100vw, 42vw" /></figure></div></section><section className="locations locations-grid"><div className="locations-grid__intro"><p>Con base en el Valle y disponible en todo Texas</p><h2>Tu DJ, donde sea la fiesta.</h2></div><div className="locations-grid__list">{rgvLocationSlugs.map((slug) => <Link href={`/es/locations/${slug}`} key={slug}><span>{locations[slug].name}</span></Link>)}<Link href="/es/locations/texas"><span>Todo Texas</span></Link></div></section><SpanishPackageBuilder /><Inquiry locale="es" title="Hagamos tu evento inolvidable." /></main><Footer locale="es" /></>; }
function Service({ item }: { item: { name: string; text: string } }) { return <><Header locale="es" /><main><section className="page-hero"><p className="eyebrow">SOUND FACTORY PRODUCTIONS</p><h1>{item.name} en McAllen y el Valle del Río Grande</h1><p>{item.text}</p></section><section className="content"><div><p className="eyebrow">VIAJES POR TEXAS</p><h2>¿Planeas fuera del Valle?</h2></div><div><p>Sound Factory Productions viaja desde McAllen para celebraciones, eventos corporativos, conciertos y eventos públicos en todo Texas.</p><Link className="text-link" href="/es/locations/texas">Explora el servicio en todo Texas →</Link></div></section><Inquiry locale="es" title={`¿Planeando ${item.name.toLowerCase()}? Hablemos.`} /></main><Footer locale="es" /></>; }
function City({ city }: { city: string }) { const statewide = city === "todo Texas"; const title = statewide ? "DJ y producción para eventos en todo Texas" : `Servicios de DJ en ${city}, Texas`; const description = statewide ? "Sound Factory Productions viaja desde McAllen para celebraciones, eventos corporativos, conciertos y eventos públicos en todo Texas." : `Sound Factory Productions lleva energía, música y producción para celebraciones en ${city} y todo Texas.`; return <><Header locale="es" /><main><section className="page-hero"><p className="eyebrow">SERVICIOS DE DJ Y PRODUCCIÓN EN TEXAS</p><h1>{title}</h1><p>{description}</p></section><section className="content"><div><p className="eyebrow">SERVICIO LOCAL</p><h2>{statewide ? "Tu evento, donde sea en Texas." : `Celebremos ${city} a todo volumen.`}</h2></div><div><p>Para bodas, quinceañeras, eventos privados, celebraciones corporativas, conciertos y eventos públicos, creamos una experiencia que tus invitados recordarán.</p><Link className="text-link" href="/es/services/wedding-dj">Explora servicios para eventos →</Link><br /><Link className="text-link" href="/es/locations/texas">Servicio de viaje en todo Texas →</Link></div></section><Inquiry locale="es" title={statewide ? "¿Planeas un evento en Texas? Hablemos." : `¿Buscas DJ en ${city}?`} /></main><Footer locale="es" /></>; }
